name: Bottlet
description: $description
version: "$version"

main: au.lupine.bottlet.Bottlet
api-version: "1.21.11"
load: POSTWORLD

authors: [jwkerr]
website: https://lupine.au

folia-supported: true

libraries:
  - org.spongepowered:configurate-gson:4.2.0

permission:
  bottlet.command.bottlet:
    description: Grants access to the Bottlet command.
    default: true

  bottlet.command.bottlet.convert:
    description: Grants access to the Bottlet convert command.
    default: true

  bottlet.command.bottlet.get:
    description: Grants access to the Bottlet get command.
    default: true

  bottlet.command.bottlet.mend:
    description: Grants access to the Bottlet mend command.
    default: true

  bottlet.command.bottlet.stats:
    description: Grants access to the Bottlet stats command.
    default: true

  bottlet.command.bottlet.stats.other:
    description: Grants access to view the Bottlet stats of other players.
    default: false

  bottlet.command.bottlet.toggle:
    description: Grants access to the Bottlet toggle command.
    default: true

  bottlet.command.bottlet.toggle.thrown:
    description: Grants access to the Bottlet toggle thrown command.
    default: true

  bottlet.command.bottlet.until:
    description: Grants access to the Bottlet until command.
    default: true

commands:
  bottlet:
    description: Command to interface with Bottlet.
    permission: bottlet.command.bottlet